table fraud_data
	lineageTag: e5d17ef1-96c6-4620-88c2-a2eea5243a7b

	column Step
		dataType: int64
		formatString: 0
		lineageTag: 5630c95a-5ed4-498f-a2c8-5140dc59c286
		summarizeBy: none
		sourceColumn: Step

		annotation SummarizationSetBy = Automatic

	column Type
		dataType: string
		lineageTag: 1b49b3c9-caf7-4874-bce3-de06546b81fb
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	column Amount_Transferred
		dataType: double
		lineageTag: a5f6c0bc-6518-4b67-b436-08e7b6bbf3d8
		summarizeBy: sum
		sourceColumn: Amount_Transferred

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Name_Orig
		dataType: string
		lineageTag: 473d50f6-c3a6-4701-adca-8a21563dadea
		summarizeBy: none
		sourceColumn: Name_Orig

		annotation SummarizationSetBy = Automatic

	column Old_Balanace_Orig
		dataType: double
		lineageTag: 8b0d7af6-5833-49b5-ba6d-86ec8d6f99d7
		summarizeBy: sum
		sourceColumn: Old_Balanace_Orig

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column New_Balance_Orog
		dataType: double
		lineageTag: f7d0f725-63c7-47ac-8458-c4cb631d3b4a
		summarizeBy: sum
		sourceColumn: New_Balance_Orog

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Name_Dest
		dataType: string
		lineageTag: 055ab163-78cf-4a68-a521-ab9bdf452805
		summarizeBy: none
		sourceColumn: Name_Dest

		annotation SummarizationSetBy = Automatic

	column Old_Balance_Dest
		dataType: double
		lineageTag: 43f07b64-378e-42b2-a087-fa3e20e18e03
		summarizeBy: sum
		sourceColumn: Old_Balance_Dest

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column New_Balance_Dest
		dataType: double
		lineageTag: 62a80df1-2d0c-406e-a0de-84b464cb0ce9
		summarizeBy: sum
		sourceColumn: New_Balance_Dest

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Balance Mismatch'
		dataType: int64
		formatString: 0
		lineageTag: b61a22d0-c3d2-49bf-a61c-5d1f73214653
		summarizeBy: sum
		sourceColumn: Balance Mismatch

		annotation SummarizationSetBy = Automatic

	column Zero_to_Zero_Dest
		dataType: int64
		formatString: 0
		lineageTag: d923cbb5-1ab9-4dee-be73-e5beaacb6cc7
		summarizeBy: sum
		sourceColumn: Zero_to_Zero_Dest

		annotation SummarizationSetBy = Automatic

	column Large_Transaction
		dataType: int64
		formatString: 0
		lineageTag: 7882a195-1bad-48e9-9e19-ba4c729ecff9
		summarizeBy: sum
		sourceColumn: Large_Transaction

		annotation SummarizationSetBy = Automatic

	column Type_sensitive
		dataType: int64
		formatString: 0
		lineageTag: 24457eac-525b-49eb-a4d0-b988c322320e
		summarizeBy: sum
		sourceColumn: Type_sensitive

		annotation SummarizationSetBy = Automatic

	column Flagged_Fraud
		dataType: int64
		formatString: 0
		lineageTag: 11412295-553b-417a-a42f-bcba347ee3f6
		summarizeBy: sum
		sourceColumn: Flagged_Fraud

		annotation SummarizationSetBy = Automatic

	column Fraud_Risk_Score
		dataType: int64
		formatString: 0
		lineageTag: 080345f3-8946-4b28-8bf7-42d5b25e7dbc
		summarizeBy: sum
		sourceColumn: Fraud_Risk_Score

		annotation SummarizationSetBy = Automatic

	partition fraud_data = m
		mode: import
		source =
				let
				    Source = Odbc.DataSource("dsn=localhost", [HierarchicalNavigation=true]),
				    fraud_analysis_Database = Source{[Name="fraud_analysis",Kind="Database"]}[Data],
				    fraud_data_Table = fraud_analysis_Database{[Name="fraud_data",Kind="Table"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(fraud_data_Table,{{"Balance_Mismatch", "Balance Mismatch"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

